### ISSUE TITLE
Website Access Issue: Insecure Connection and World4You Parking Page

### ISSUE THREAD

**Issue by ciruz** [Zumpel96/Teuerungsportal#101]
The site is accessible without HTTPS, and when you visit it, you will be directed to a World4You parking page.

Example: 
http://teuerungsportal.at/
http://www.teuerungsportal.at/

**Comment by Zumpel96** [comment]
Ah, thanks for the Info! Will fix that ASAP.

**Comment by Zumpel96** [comment]
Done. Should have been a caching issue on the nameservers.
