### ISSUE TITLE
Allow recategorizaton of products

### ISSUE THREAD

**Issue by Woazboat** [Zumpel96/Teuerungsportal#123]
Currently there is no way to change the category of a product when it already has one. Products that are falsely categorized therefore cannot be fixed/moved to the correct category. 

A report/moderation queue to flag errors might work here if users shouldn't be able to freely change the category of already categorized products.

e.g. https://teuerungsportal.at/stores/Spar/2020002408572

**Comment by Zumpel96** [comment]
Categorization will be automated in the future and can only be done by admins
