### ISSUE TITLE
Product links to Spar are partly broken

### ISSUE THREAD

**Issue by schneebly-defender** [Zumpel96/Teuerungsportal#129]
E.g. this product:
https://teuerungsportal.at/stores/Spar/2020001630950

The link to the online shop leads to a 404 error.
Probably the URL in the spar webshop changed since the record was created in the teuerungsportal.
The SPAR data fetcher doesn't seem to update the URL for existing products (only prices).

Suggestion would be to update the URL along the prices in the neighbourhood of this line:
https://github.com/Zumpel96/Teuerungsportal/blob/59da9ae529a30d89b08c045d5cba442527d35c00/Teuerungsportal/Extractors/Spar/SparDataExtractor.cs#L115

**Comment by schneebly-defender** [comment]
@Zumpel96 Lemme know your policies, would you want people to create PRs?

**Comment by Zumpel96** [comment]
The problem is not, that the URL changed, but the DB columns size is too small. Gonna change from 64 chars to 128. However, the URL needs to be updated nevertheless, to fix all broken ones.
