### ISSUE TITLE
+/- Anzeige bei gesunkenem/gestiegenem Preis

### ISSUE THREAD

**Issue by hb02** [Zumpel96/Teuerungsportal#99]
Hallo,

erstmal --> **Respekt**, Top Arbeit

Ich weiß nicht wie du das siehst, aber intuitiver wäre in der Übersicht bzw. generell bei gefallenen/gestiegenen Preisen ein Pfeil od zumindest +/- davor anzuzeigen. Rot/Grün sind zwar hervorragende Marker, aber beim arbeiten mit zahlen wäre eine +/- Notation meiner Meinung nach bessern.

eventuell -0,10€/-1.0% (Pfeil nach unten)
bzw +0,10€/+1.0% (Pfeil nach oben)
und evnetuell (optional) bei stagnation (denke nicht, dass du deine werte denn in der db aktualisierst)  +/- 0€ / 0% -->

![image](https://github.com/Zumpel96/Teuerungsportal/assets/6522865/b5034e80-9138-4a45-bb3c-309ca3844c15)

**Comment by Zumpel96** [comment]
Hi! Thanks! Will be added in the next release! Nice Idea
